---
sources:
  - Samaano.designspace

familyName: Samaano
outputDir: ../fonts
vfDir: $outputDir/variable
#ttDir: $outputDir/ttf
#otDir: $outputDir/otf
woffDir: $outputDir/webfonts
buildVariable: true
buildStatic: false
buildTTF: true
buildOTF: true
buildSmallCap: true
autohintTTF: true
includeSourceFixes: true
flattenComponents: true
decomposeTransformedComponents: true
checkCompatibility: true
splitItalic: false
axisOrder:
  - slnt
  - wdth
  - wght
stat:
    - name: Width
      tag: wdth
      values:
      - name: Normal
        value: 100
        flags: 2
      - name: SemiExpanded
        value: 112.5
      - name: Expanded
        value: 125
      - name: ExtraExpanded
        value: 150
      - name: UltraExpanded
        value: 200
    - name: Weight
      tag: wght
      values:
      - name: Thin
        value: 100
      - name: ExtraLight
        value: 200
      - name: Light
        value: 300
      - name: Regular
        value: 400
        linkedValue: 700
        flags: 2
      - name: Medium
        value: 500
      - name: SemiBold
        value: 600
      - name: Bold
        value: 700
    - name: Slant
      tag: slnt
      values: 
      - name: Default
        value: 0
        linkedValue: 1
        flags: 2
      - name: Oblique
        value: -20

